### ISSUE TITLE
Question about the w,h after image preprocess?

### ISSUE THREAD

**Issue by XiaXuehai** [YoungGer/Faster-RCNN-Pytorch#1]
After the image data  pass preprocess function in dataset.py, the size of image is in range(600, 1000), but it is not fixed.
So how to do the next step.i.e through the net vgg16, the featrue size is not the same.

**Comment by BearVic** [comment]
@XiaXuehai This model used the conv layers of vgg16 only, I think that's why it does not need the fixed size of the input images.

**Comment by XiaXuehai** [comment]
@BearVic I read the codes and the size of feature map will be unified on the `VGG16RoIHead`, but it has to take one image at one time to the net when training.

**Comment by BearVic** [comment]
@XiaXuehai Because dataloader requires every data in the batch to be the same shape. So I guess the author set batch_size to 1 for convenience.
